startLocation:
  world: world
  a:
    x: 129
    y: 76
    z: 93
    yaw: 0
  b:
    x: 129
    y: 76
    z: 105
    yaw: 180
spawnLocation:
  x: 124
  y: 77
  z: 98
  yaw: 90
inventory:
- 272
- 306
- 307
- 308
- 309
- 261
- 262