name: Tournament
main: to.joe.j2mc.tournament.J2MC_Tournament
version: 0.1
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Tournament module.
commands:
  join:
    description: Add yourself to the tournament
    usage: /join
    permission: j2mc.tournament.join
    permission-message: You may not join the tournament
  leave:
    description: Remove yourself from the tournament
    usage: /leave
    permission: j2mc.tournament.leave
    permission-message: You may not leave the tournament
  duel:
    description: Duel administration commands
    usage: /duel
    permission: j2mc.tournament.admin.duel
    permission-message: No
permissions:
  j2mc.tournament.join:
    description: Join a tournament
  j2mc.tournament.leave:
    description: Leave a tournament
  j2mc.tournament.duel:
    description: Administrate a tournament